#!/bin/bash

trap 'kill %1; kill %2' 0 1 2 3 13 15
npm run devBuild | tee /dev/null | sed -e 's/^/[Webpack] /' & npm run devStart | tee /dev/null | sed -e 's/^/[PeerJS] /' & python manage.py runserver | tee /dev/null | sed -e 's/^/[Django] /'