# Generated by Django 3.1 on 2020-08-15 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='location',
            new_name='city',
        ),
    ]
