# Generated by Django 3.1 on 2020-08-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200815_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
