# Generated by Django 3.1 on 2020-08-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200819_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='cashapp_qr',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='paypal_qr',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='venmo_qr',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
