# Generated by Django 3.1 on 2020-08-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200820_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='headshot',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
