# Generated by Django 3.1 on 2020-08-23 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200820_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musiciancomment',
            options={'ordering': ['date_created']},
        ),
        migrations.RenameField(
            model_name='musiciancomment',
            old_name='body',
            new_name='message',
        ),
    ]
