# Generated by Django 3.1 on 2020-08-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200823_0115'),
        ('core', '0010_musician_favorited_by'),
    ]

    operations = [
    ]
