# Generated by Django 3.1 on 2020-08-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20200823_1745'),
        ('core', '0011_merge_20200823_1921'),
    ]

    operations = [
    ]
