# Generated by Django 3.1 on 2020-08-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200823_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
