# Generated by Django 3.1 on 2020-08-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200823_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
