# Generated by Django 3.1 on 2020-08-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200827_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='viewers',
            field=models.IntegerField(default=0),
        ),
    ]
