# Generated by Django 3.1 on 2020-08-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200827_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='genre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
