# Generated by Django 3.1 on 2020-08-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_event_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
