# Generated by Django 3.1 on 2020-08-31 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_event_viewers'),
        ('core', '0017_auto_20200829_1933'),
    ]

    operations = [
    ]
